class PasswordError(ValueError):
    pass


class UserNotFound(Exception):
    pass
